### ISSUE TITLE
Cohort View support in SMILE dashboard

### ISSUE THREAD

**Issue by ao508** [mskcc/smile-server#1089]
Example use case:
- How many cohorts were delivered in a certain time frame?

Notes:
- Samples can be part of multiple cohorts. PMs want to be able to look at what cohorts a sample is associated with as well as search by cohort id to see what samples were delivered as part of that cohort (searchable by either direction)
- Adding a concat string of cohort IDs for each sample is helpful but doesn't provide the delivery date which is something PMs need to query by or have accessible when looking these up
- However, adding a concat string of cohort IDs would still be nice on a per-sample basis. Can possibly make cohort IDs clickable to easily bring up the cohort view page for that cohort

_______

request 08944_B has mocked data for prototyping Cohort View tab dev.

- [x] example data in db (cohort complete, bam complete, qc, complete, maf complete sample events)
- [ ] graphql model update (can be derived/auto-generated from having mocked data in the dev graphdb)
- [ ] tempo message workflow in place (can work without this but would be nice to have) **in progress**

Tempo tracker screenshot:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fa43fc44906e70b2de988c4d02223d1900e735e/image.png" alt="image.png" />

HERA tracker:
1. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFJiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dd144f296ccb03491eca349054a468bc3648316/image.png" alt="image.png" />

2.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c0e31ef0e5ff57093307886debfbe0e1acabdc3/image.png" alt="image.png" />

3.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5903f92d0da0afdf757c16845692b26b639f6b7/image.png" alt="image.png" />

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/smile-server/1089?planning-poker) with Zenhub @qu8n
